//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZYStudentGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YZYStudentGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string column_address {
            get {
                return ResourceManager.GetString("column_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string column_amount {
            get {
                return ResourceManager.GetString("column_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string column_category {
            get {
                return ResourceManager.GetString("column_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Description.
        /// </summary>
        public static string column_category_description {
            get {
                return ResourceManager.GetString("column_category_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID.
        /// </summary>
        public static string column_category_id {
            get {
                return ResourceManager.GetString("column_category_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        public static string column_cell {
            get {
                return ResourceManager.GetString("column_cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string column_city {
            get {
                return ResourceManager.GetString("column_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string column_confirm_password {
            get {
                return ResourceManager.GetString("column_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID.
        /// </summary>
        public static string column_course_id {
            get {
                return ResourceManager.GetString("column_course_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string column_course_name {
            get {
                return ResourceManager.GetString("column_course_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string column_difficulty {
            get {
                return ResourceManager.GetString("column_difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string column_email {
            get {
                return ResourceManager.GetString("column_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string column_end_date {
            get {
                return ResourceManager.GetString("column_end_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string column_evaluation_comment {
            get {
                return ResourceManager.GetString("column_evaluation_comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluation Date.
        /// </summary>
        public static string column_evaluation_evdate {
            get {
                return ResourceManager.GetString("column_evaluation_evdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string column_first_name {
            get {
                return ResourceManager.GetString("column_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string column_gender {
            get {
                return ResourceManager.GetString("column_gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string column_last_name {
            get {
                return ResourceManager.GetString("column_last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string column_middle_name {
            get {
                return ResourceManager.GetString("column_middle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string column_password {
            get {
                return ResourceManager.GetString("column_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Account.
        /// </summary>
        public static string column_pay_account {
            get {
                return ResourceManager.GetString("column_pay_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Date.
        /// </summary>
        public static string column_pay_date {
            get {
                return ResourceManager.GetString("column_pay_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment ID.
        /// </summary>
        public static string column_payment_id {
            get {
                return ResourceManager.GetString("column_payment_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string column_phone {
            get {
                return ResourceManager.GetString("column_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string column_photo {
            get {
                return ResourceManager.GetString("column_photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string column_postal_code {
            get {
                return ResourceManager.GetString("column_postal_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string column_province {
            get {
                return ResourceManager.GetString("column_province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string column_start_date {
            get {
                return ResourceManager.GetString("column_start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Name.
        /// </summary>
        public static string column_street_name {
            get {
                return ResourceManager.GetString("column_street_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Number.
        /// </summary>
        public static string column_street_no {
            get {
                return ResourceManager.GetString("column_street_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Name.
        /// </summary>
        public static string column_teacher_name {
            get {
                return ResourceManager.GetString("column_teacher_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuition.
        /// </summary>
        public static string column_tuition {
            get {
                return ResourceManager.GetString("column_tuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string column_user_id {
            get {
                return ResourceManager.GetString("column_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string column_user_name {
            get {
                return ResourceManager.GetString("column_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string column_user_role {
            get {
                return ResourceManager.GetString("column_user_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIN.
        /// </summary>
        public static string column_user_sin {
            get {
                return ResourceManager.GetString("column_user_sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one on one section.
        /// </summary>
        public static string content_1_on_1_session {
            get {
                return ResourceManager.GetString("content_1_on_1_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 meters from the metro station.
        /// </summary>
        public static string content_100_meters_from_metro_station {
            get {
                return ResourceManager.GetString("content_100_meters_from_metro_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4-8 students per class.
        /// </summary>
        public static string content_4_8_students_per_class {
            get {
                return ResourceManager.GetString("content_4_8_students_per_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Accounts.
        /// </summary>
        public static string content_account_number {
            get {
                return ResourceManager.GetString("content_account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string content_account_tab {
            get {
                return ResourceManager.GetString("content_account_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string content_add {
            get {
                return ResourceManager.GetString("content_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string content_add_button {
            get {
                return ResourceManager.GetString("content_add_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string content_adduser_dialog {
            get {
                return ResourceManager.GetString("content_adduser_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string content_balance {
            get {
                return ResourceManager.GetString("content_balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string content_cancel_button {
            get {
                return ResourceManager.GetString("content_cancel_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo.
        /// </summary>
        public static string content_card_detail {
            get {
                return ResourceManager.GetString("content_card_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string content_contact_us {
            get {
                return ResourceManager.GetString("content_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string content_convenient_transportation {
            get {
                return ResourceManager.GetString("content_convenient_transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Courses.
        /// </summary>
        public static string content_course_number {
            get {
                return ResourceManager.GetString("content_course_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string content_course_tab {
            get {
                return ResourceManager.GetString("content_course_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string content_delete {
            get {
                return ResourceManager.GetString("content_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string content_delete_button {
            get {
                return ResourceManager.GetString("content_delete_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-LEARNING.
        /// </summary>
        public static string content_e_learning {
            get {
                return ResourceManager.GetString("content_e_learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit to support online learning.
        /// </summary>
        public static string content_e_learning_toolkit {
            get {
                return ResourceManager.GetString("content_e_learning_toolkit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string content_edit {
            get {
                return ResourceManager.GetString("content_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User.
        /// </summary>
        public static string content_edituser_dialog {
            get {
                return ResourceManager.GetString("content_edituser_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTRA TUTORING.
        /// </summary>
        public static string content_extra_tutoring {
            get {
                return ResourceManager.GetString("content_extra_tutoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followed.
        /// </summary>
        public static string content_followed {
            get {
                return ResourceManager.GetString("content_followed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female ,Male, Other, Unknown.
        /// </summary>
        public static string content_gender_options {
            get {
                return ResourceManager.GetString("content_gender_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string content_login {
            get {
                return ResourceManager.GetString("content_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus consequat ligula et ornare rutrum. Suspendisse vel nibh massa. Sed maximus porta augue eget viverra. Sed ullamcorper interdum ligula. Aenean vitae..
        /// </summary>
        public static string content_lorem {
            get {
                return ResourceManager.GetString("content_lorem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Course.
        /// </summary>
        public static string content_manage_course {
            get {
                return ResourceManager.GetString("content_manage_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string content_manage_payment {
            get {
                return ResourceManager.GetString("content_manage_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string content_manage_profile {
            get {
                return ResourceManager.GetString("content_manage_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Courses.
        /// </summary>
        public static string content_open_courses {
            get {
                return ResourceManager.GetString("content_open_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPTIMIZED GROUP SIZE.
        /// </summary>
        public static string content_optimized_group_size {
            get {
                return ResourceManager.GetString("content_optimized_group_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Courses.
        /// </summary>
        public static string content_our_courses {
            get {
                return ResourceManager.GetString("content_our_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Teachers.
        /// </summary>
        public static string content_our_teachers {
            get {
                return ResourceManager.GetString("content_our_teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Tuition.
        /// </summary>
        public static string content_paid_tuition {
            get {
                return ResourceManager.GetString("content_paid_tuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string content_pay {
            get {
                return ResourceManager.GetString("content_pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PERSONALIZED.
        /// </summary>
        public static string content_personalized {
            get {
                return ResourceManager.GetString("content_personalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Picture.
        /// </summary>
        public static string content_pick_picture {
            get {
                return ResourceManager.GetString("content_pick_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string content_profile_tab {
            get {
                return ResourceManager.GetString("content_profile_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string content_register {
            get {
                return ResourceManager.GetString("content_register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string content_register_button {
            get {
                return ResourceManager.GetString("content_register_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Courses.
        /// </summary>
        public static string content_registered_courses {
            get {
                return ResourceManager.GetString("content_registered_courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string content_reset {
            get {
                return ResourceManager.GetString("content_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string content_search_button {
            get {
                return ResourceManager.GetString("content_search_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign On.
        /// </summary>
        public static string content_signon_button {
            get {
                return ResourceManager.GetString("content_signon_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SINCE 1999.
        /// </summary>
        public static string content_since_1999 {
            get {
                return ResourceManager.GetString("content_since_1999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skillful teachers with rich experience.
        /// </summary>
        public static string content_skillful_teachers_with_rich_experience {
            get {
                return ResourceManager.GetString("content_skillful_teachers_with_rich_experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to study plan.
        /// </summary>
        public static string content_study_plan {
            get {
                return ResourceManager.GetString("content_study_plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string content_submit_button {
            get {
                return ResourceManager.GetString("content_submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Details.
        /// </summary>
        public static string content_teacher_course_tab {
            get {
                return ResourceManager.GetString("content_teacher_course_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Summary.
        /// </summary>
        public static string content_teacher_courses_tab {
            get {
                return ResourceManager.GetString("content_teacher_courses_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string content_teacher_tab {
            get {
                return ResourceManager.GetString("content_teacher_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Courses List.
        /// </summary>
        public static string content_teacher_tab_title {
            get {
                return ResourceManager.GetString("content_teacher_tab_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Students.
        /// </summary>
        public static string content_total_students {
            get {
                return ResourceManager.GetString("content_total_students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuition Total.
        /// </summary>
        public static string content_tuition_total {
            get {
                return ResourceManager.GetString("content_tuition_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string content_update {
            get {
                return ResourceManager.GetString("content_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string content_update_button {
            get {
                return ResourceManager.GetString("content_update_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHY CHOOSE YZY.
        /// </summary>
        public static string content_why_choose_yzy {
            get {
                return ResourceManager.GetString("content_why_choose_yzy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid input of course ID.
        /// </summary>
        public static string error_course_id {
            get {
                return ResourceManager.GetString("error_course_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid input of full name.
        /// </summary>
        public static string error_full_name {
            get {
                return ResourceManager.GetString("error_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YZY School.
        /// </summary>
        public static string windows_title {
            get {
                return ResourceManager.GetString("windows_title", resourceCulture);
            }
        }
    }
}
