//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZYLibraryAzure
{
    using System;
    
    public enum GenderEnum : int
    {
        Female = 1,
        Male = 2,
        Other = 3,
        Unknown = 4
    }
}
